# Generated by Django 4.2.1 on 2023-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=15)),
                ('descrition', models.TextField(default='descrition', max_length=1000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=1)),
                ('experiance', models.IntegerField(default=1)),
            ],
        ),
    ]
