# Generated by Django 4.2.1 on 2023-05-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.categ'),
            preserve_default=False,
        ),
    ]
